### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by hse2527** [KSEAWisconsin/kseawisconsin.github.io#32]
for FireFox
- [x] more information button does not lead to the new website
- [x] upcoming event grid clicks do not proceed to the next level
- [x] about us page's personal website hyperlink does not work
- [x] taskforce hyperlink on the bottom of the page does not work
- [x] "VIEW MORE EVENTS AND NEWS" should be "VIEW MORE NEWS AND EVENTS" on the bottom of page home

**Comment by hse2527** [comment]
Firefox / Chrome
- [x] about us page's personal website hyperlink does not work
- [x] "VIEW MORE EVENTS AND NEWS" should be "VIEW MORE NEWS AND EVENTS" on the bottom of page home
- [x] pictures for the taskforce

**Comment by hyecheol123** [comment]
- [x] Make Task Force to Bold + Diff Color

**Comment by hyecheol123** [comment]
- [x] Does not support IE / Need to fix

**Comment by hyecheol123** [comment]
- [x] favicon.ico
