### ISSUE TITLE
Code Header for Desktop

### ISSUE THREAD

**Issue by hyecheol123** [KSEAWisconsin/kseawisconsin.github.io#6]

**Comment by Drag-yong** [comment]
The file is in my branch Yongsang_HTML

**Comment by hyecheol123** [comment]
@Drag-yong 

Additional required Feature
- [x] Highlight current
- [x] When hovering, indicate the hovering element by underline
  - [x] Animation for indicating underline (Appear from the middle)

Related File:
**html doc**: _includes/header.html
**stylesheet**: _sass/KSEAWeb.scss

**Comment by hyecheol123** [comment]
Update on **Highlight current**

Current menu's link has been indicated by **active** tag, **need to set proper CSS for active**

**Comment by hyecheol123** [comment]
Update on **Highlight current**: Complete

**Comment by hyecheol123** [comment]
Update: **Hovering** Completed
